# Generated by Django 5.2.10 on 2026-01-20 14:53

from django.db import migrations, models


def forwards_role_values(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.filter(role="DIRECTOR").update(role="DIRECTEUR")
    User.objects.filter(role="TRAINER").update(role="FORMATEUR")
    User.objects.filter(role="STUDENT").update(role="ETUDIANT")


def backwards_role_values(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.filter(role="DIRECTEUR").update(role="DIRECTOR")
    User.objects.filter(role="FORMATEUR").update(role="TRAINER")
    User.objects.filter(role="ETUDIANT").update(role="STUDENT")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_role_values, backwards_role_values),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DIRECTEUR', 'Directeur'), ('FORMATEUR', 'Formateur'), ('ETUDIANT', 'Étudiant')], default='ETUDIANT', max_length=20),
        ),
    ]
