# Generated by Django 5.2.10 on 2026-01-20 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PedagogicalSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spaces', to='academics.promotion')),
                ('students', models.ManyToManyField(blank=True, related_name='spaces', to='academics.studentprofile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spaces', to='academics.subject')),
                ('trainers', models.ManyToManyField(blank=True, related_name='trainer_spaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', 'subject__code'],
                'constraints': [models.UniqueConstraint(fields=('subject', 'year'), name='uniq_space_subject_year')],
            },
        ),
    ]
